version: "2.2"
services:
  app:
    build: ./app/
    container_name: ebi-parser
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  db:
    build: ./db/
    image: postgres
    container_name: db
    ports:
      - 5435:5432
    expose:
      - "5435"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  
