version: "2.2"
services:
  app :
    build: ./app/
    links:
      - db
  db:
    build: ./db/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: compoundparser
      POSTGRES_PASSWORD: secrekt
