version: "3.8"
services:
  app :
    build: ./app/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    build: ./db/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5